# Generated by Django 4.2.2 on 2023-06-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('roll', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('vote', models.CharField(max_length=200)),
            ],
        ),
    ]
